" Name:         Bionik 2
" Description:  Second version of my bionik colorscheme
" Author:       Marvin Dostal
" Maintainer:   Marvin Dostal
" Website:      https://github.com/datMaffin/vim-colors-bionik2
" License:      Public domain
" Last Updated: Thu 02 Feb 2023 19:34:44

" Generated by Colortemplate v2.2.0

hi clear
let g:colors_name = 'bionik2'

let s:t_Co = exists('&t_Co') && !has('gui_running') ? (&t_Co ?? 0) : -1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Float Number
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#2e3436', '#e60000', '#32cd32', '#e66e00', '#0061a5', '#b30070', '#0db1a7', '#ffd7a2', '#555753', '#ff3236', '#34ee34', '#ffa552', '#5ea9e9', '#ec4fb1', '#4bcbcf', '#ffffff']
  endif
  hi Normal guifg=#d2b48c guibg=#062626 gui=NONE cterm=NONE
  hi Terminal guifg=#d2b48c guibg=#062626 gui=NONE cterm=NONE
  hi IncSearch guifg=#d2b48c guibg=#0061a5 gui=reverse cterm=reverse
  hi Search guifg=#0061a5 guibg=#d2b48c gui=reverse cterm=reverse
  hi Visual guifg=#555753 guibg=#ffffff gui=reverse cterm=reverse
  hi LineNr guifg=#ffd7a2 guibg=#555753 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ffd7a2 guibg=#2e3436 gui=bold cterm=bold
  hi FoldColumn guifg=#0db1a7 guibg=NONE gui=reverse cterm=reverse
  hi Folded guifg=#0db1a7 guibg=NONE gui=italic,reverse cterm=italic,reverse
  hi ColorColumn guifg=NONE guibg=#2e3436 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#2e3436 gui=NONE cterm=NONE
  hi MatchParen guifg=#e66e00 guibg=NONE gui=reverse cterm=reverse
  hi StatusLine guifg=NONE guibg=#0061a5 gui=bold cterm=bold
  hi Pmenu guifg=#2e3436 guibg=#ffd7a2 gui=NONE cterm=NONE
  hi PmenuSel guifg=#ffd7a2 guibg=#0061a5 gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Error guifg=#e60000 guibg=NONE gui=bold,reverse cterm=bold,reverse
  hi ErrorMsg guifg=#e60000 guibg=NONE gui=reverse cterm=reverse
  hi WarningMsg guifg=#e66e00 guibg=NONE gui=reverse cterm=reverse
  hi Constant guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Boolean guifg=#e60000 guibg=NONE gui=bold cterm=bold
  hi String guifg=#e60000 guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#e60000 guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#e60000 guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#0db1a7 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#5ea9e9 guibg=NONE gui=bold,italic cterm=bold,italic
  hi Comment guifg=#32cd32 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#e66e00 guibg=#2e3436 gui=italic,reverse,underline cterm=italic,reverse,underline
  hi Special guifg=#ec4fb1 guibg=NONE gui=NONE cterm=NONE
  hi Title guifg=#5ea9e9 guibg=NONE gui=bold,underline cterm=bold,underline
  hi PreProc guifg=#e66e00 guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#b30070 guibg=NONE gui=bold,italic cterm=bold,italic
  hi DiffAdd guifg=#32cd32 guibg=#ffffff gui=bold,reverse cterm=bold,reverse
  hi DiffChange guifg=#e66e00 guibg=#ffffff gui=italic,reverse cterm=italic,reverse
  hi DiffDelete guifg=#e60000 guibg=#ffffff gui=italic,reverse cterm=italic,reverse
  hi DiffText guifg=#b30070 guibg=#ffffff gui=bold,reverse cterm=bold,reverse
  hi SpellBad guifg=NONE guibg=NONE guisp=#e60000 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellCap guifg=NONE guibg=NONE guisp=#0061a5 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellLocal guifg=NONE guibg=NONE guisp=#b30070 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellRare guifg=NONE guibg=NONE guisp=#0db1a7 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Ignore guifg=#555753 guibg=NONE gui=italic cterm=italic
  hi NonText guifg=#0061a5 guibg=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=reverse cterm=reverse
    hi Statement gui=bold cterm=bold
    hi Todo gui=reverse,underline cterm=reverse,underline
    hi Type gui=bold cterm=bold
    hi DiffChange gui=reverse cterm=reverse
    hi DiffDelete gui=reverse cterm=reverse
    hi Ignore gui=NONE cterm=NONE
  endif
else
  " Light background
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#252525', '#e60000', '#00b800', '#e66e00', '#0a5594', '#b30070', '#00988e', '#cccccc', '#7f7f7f', '#ff3236', '#34ee34', '#ffa552', '#428ecf', '#ec4fb1', '#4bcbcf', '#ededed']
  endif
  hi Normal guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi Terminal guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi IncSearch guifg=#ffa552 guibg=#000000 gui=reverse cterm=reverse
  hi Search guifg=#428ecf guibg=#000000 gui=reverse cterm=reverse
  hi Visual guifg=#7f7f7f guibg=#ededed gui=reverse cterm=reverse
  hi LineNr guifg=NONE guibg=#cccccc gui=NONE cterm=NONE
  hi CursorLineNr guifg=NONE guibg=#ededed gui=bold cterm=bold
  hi FoldColumn guifg=#00988e guibg=NONE gui=reverse cterm=reverse
  hi Folded guifg=#00988e guibg=NONE gui=italic,reverse cterm=italic,reverse
  hi ColorColumn guifg=NONE guibg=#ededed gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#ededed gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=#ffa552 gui=NONE cterm=NONE
  hi StatusLine guifg=#0a5594 guibg=NONE gui=bold,reverse cterm=bold,reverse
  hi Pmenu guifg=#252525 guibg=#cccccc gui=NONE cterm=NONE
  hi PmenuSel guifg=#252525 guibg=#428ecf gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Error guifg=#e60000 guibg=NONE gui=bold,reverse cterm=bold,reverse
  hi ErrorMsg guifg=#e60000 guibg=NONE gui=reverse cterm=reverse
  hi WarningMsg guifg=#e66e00 guibg=NONE gui=reverse cterm=reverse
  hi Constant guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Boolean guifg=#e60000 guibg=NONE gui=bold cterm=bold
  hi String guifg=#e60000 guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#e60000 guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#e60000 guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#00988e guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#0a5594 guibg=NONE gui=bold,italic cterm=bold,italic
  hi Comment guifg=#00b800 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#ffa552 guibg=#0a5594 gui=italic,reverse,underline cterm=italic,reverse,underline
  hi Special guifg=#b30070 guibg=NONE gui=NONE cterm=NONE
  hi Title guifg=#0a5594 guibg=NONE gui=bold,underline cterm=bold,underline
  hi PreProc guifg=#e66e00 guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#b30070 guibg=NONE gui=bold,italic cterm=bold,italic
  hi DiffAdd guifg=#00b800 guibg=#ededed gui=bold,reverse cterm=bold,reverse
  hi DiffChange guifg=#e66e00 guibg=#ededed gui=italic,reverse cterm=italic,reverse
  hi DiffDelete guifg=#e60000 guibg=#ededed gui=italic,reverse cterm=italic,reverse
  hi DiffText guifg=#b30070 guibg=#ededed gui=bold,reverse cterm=bold,reverse
  hi SpellBad guifg=NONE guibg=NONE guisp=#e60000 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellCap guifg=NONE guibg=NONE guisp=#0a5594 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellLocal guifg=NONE guibg=NONE guisp=#b30070 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellRare guifg=NONE guibg=NONE guisp=#00988e gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Ignore guifg=#cccccc guibg=NONE gui=italic cterm=italic
  if !s:italics
    hi Folded gui=reverse cterm=reverse
    hi Statement gui=bold cterm=bold
    hi Todo gui=reverse,underline cterm=reverse,underline
    hi Type gui=bold cterm=bold
    hi DiffChange gui=reverse cterm=reverse
    hi DiffDelete gui=reverse cterm=reverse
    hi Ignore gui=NONE cterm=NONE
  endif
endif

if s:t_Co >= 16
  if &background ==# 'dark'
    hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi IncSearch ctermfg=DarkYellow ctermbg=White cterm=reverse
    hi Search ctermfg=DarkBlue ctermbg=White cterm=reverse
    hi Visual ctermfg=DarkGrey ctermbg=White cterm=reverse
    hi LineNr ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
    hi CursorLineNr ctermfg=LightGrey ctermbg=Black cterm=bold
    hi FoldColumn ctermfg=DarkCyan ctermbg=NONE cterm=reverse
    hi Folded ctermfg=DarkCyan ctermbg=NONE cterm=italic,reverse
    hi ColorColumn ctermfg=NONE ctermbg=Black cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
    hi MatchParen ctermfg=DarkYellow ctermbg=NONE cterm=reverse
    hi StatusLine ctermfg=NONE ctermbg=DarkBlue cterm=bold
    hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi PmenuSel ctermfg=LightGrey ctermbg=DarkBlue cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi Error ctermfg=DarkRed ctermbg=NONE cterm=bold,reverse
    hi ErrorMsg ctermfg=DarkRed ctermbg=NONE cterm=reverse
    hi WarningMsg ctermfg=DarkYellow ctermbg=NONE cterm=reverse
    hi Constant ctermfg=NONE ctermbg=NONE cterm=bold
    hi Boolean ctermfg=DarkRed ctermbg=NONE cterm=bold
    hi String ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi Character ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi Number ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=DarkCyan ctermbg=NONE cterm=NONE
    hi Statement ctermfg=LightBlue ctermbg=NONE cterm=bold,italic
    hi Comment ctermfg=DarkGreen ctermbg=NONE cterm=NONE
    hi Todo ctermfg=DarkYellow ctermbg=Black cterm=italic,reverse,underline
    hi Special ctermfg=LightMagenta ctermbg=NONE cterm=NONE
    hi Title ctermfg=LightBlue ctermbg=NONE cterm=bold,underline
    hi PreProc ctermfg=DarkYellow ctermbg=NONE cterm=NONE
    hi Type ctermfg=DarkMagenta ctermbg=NONE cterm=bold,italic
    hi DiffAdd ctermfg=DarkGreen ctermbg=White cterm=bold,reverse
    hi DiffChange ctermfg=DarkYellow ctermbg=White cterm=italic,reverse
    hi DiffDelete ctermfg=DarkRed ctermbg=White cterm=italic,reverse
    hi DiffText ctermfg=DarkMagenta ctermbg=White cterm=bold,reverse
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=underline
    hi Ignore ctermfg=DarkGrey ctermbg=NONE cterm=italic
    hi NonText ctermfg=DarkBlue ctermbg=NONE cterm=NONE
    if !s:italics
      hi Folded cterm=reverse
      hi Statement cterm=bold
      hi Todo cterm=reverse,underline
      hi Type cterm=bold
      hi DiffChange cterm=reverse
      hi DiffDelete cterm=reverse
      hi Ignore cterm=NONE
    endif
  else
    " Light background
    hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi IncSearch ctermfg=LightYellow ctermbg=Black cterm=reverse
    hi Search ctermfg=LightBlue ctermbg=Black cterm=reverse
    hi Visual ctermfg=DarkGrey ctermbg=White cterm=reverse
    hi LineNr ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi CursorLineNr ctermfg=NONE ctermbg=White cterm=bold
    hi FoldColumn ctermfg=DarkCyan ctermbg=NONE cterm=reverse
    hi Folded ctermfg=DarkCyan ctermbg=NONE cterm=italic,reverse
    hi ColorColumn ctermfg=NONE ctermbg=White cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=White cterm=NONE
    hi MatchParen ctermfg=NONE ctermbg=LightYellow cterm=NONE
    hi StatusLine ctermfg=DarkBlue ctermbg=NONE cterm=bold,reverse
    hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi PmenuSel ctermfg=Black ctermbg=LightBlue cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi Error ctermfg=DarkRed ctermbg=NONE cterm=bold,reverse
    hi ErrorMsg ctermfg=DarkRed ctermbg=NONE cterm=reverse
    hi WarningMsg ctermfg=DarkYellow ctermbg=NONE cterm=reverse
    hi Constant ctermfg=NONE ctermbg=NONE cterm=bold
    hi Boolean ctermfg=DarkRed ctermbg=NONE cterm=bold
    hi String ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi Character ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi Number ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=DarkCyan ctermbg=NONE cterm=NONE
    hi Statement ctermfg=DarkBlue ctermbg=NONE cterm=bold,italic
    hi Comment ctermfg=DarkGreen ctermbg=NONE cterm=NONE
    hi Todo ctermfg=LightYellow ctermbg=DarkBlue cterm=italic,reverse,underline
    hi Special ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
    hi Title ctermfg=DarkBlue ctermbg=NONE cterm=bold,underline
    hi PreProc ctermfg=DarkYellow ctermbg=NONE cterm=NONE
    hi Type ctermfg=DarkMagenta ctermbg=NONE cterm=bold,italic
    hi DiffAdd ctermfg=DarkGreen ctermbg=White cterm=bold,reverse
    hi DiffChange ctermfg=DarkYellow ctermbg=White cterm=italic,reverse
    hi DiffDelete ctermfg=DarkRed ctermbg=White cterm=italic,reverse
    hi DiffText ctermfg=DarkMagenta ctermbg=White cterm=bold,reverse
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=underline
    hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=italic
    if !s:italics
      hi Folded cterm=reverse
      hi Statement cterm=bold
      hi Todo cterm=reverse,underline
      hi Type cterm=bold
      hi DiffChange cterm=reverse
      hi DiffDelete cterm=reverse
      hi Ignore cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: gui_fg               #d2b48c                ~
" Color: gui_bg               #062626                ~
" Color: green                #32CD32                ~        DarkGreen
" Color: black                #2e3436                ~        Black
" Color: brightblack          #555753                ~        DarkGrey
" Color: white                #ffd7a2                ~        LightGrey
" Color: brightwhite          #ffffff                ~        White
" Color: red                  #e60000                ~        DarkRed
" Color: yellow               #e66e00                ~        DarkYellow
" Color: blue                 #0061a5                ~        DarkBlue
" Color: magenta              #b30070                ~        DarkMagenta
" Color: cyan                 #0db1a7                ~        DarkCyan
" Color: brightred            #ff3236                ~        LightRed
" Color: brightgreen          #34ee34                ~        LightGreen
" Color: brightyellow         #ffa552                ~        LightYellow
" Color: brightblue           #5ea9e9                ~        LightBlue
" Color: brightmagenta        #ec4fb1                ~        LightMagenta
" Color: brightcyan           #4bcbcf                ~        LightCyan
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" Background: light
" Color: gui_fg               #000000                ~        none
" Color: gui_bg               #ffffff                ~        none
" Color: black                #252525                ~        Black
" Color: red                  #e60000                ~        DarkRed
" Color: green                #00B800                ~        DarkGreen
" Color: yellow               #e66e00                ~        DarkYellow
" Color: blue                 #0a5594                ~        DarkBlue
" Color: magenta              #b30070                ~        DarkMagenta
" Color: cyan                 #00988e                ~        DarkCyan
" Color: white                #cccccc                ~        LightGrey
" Color: brightblack          #7f7f7f                ~        DarkGrey
" Color: brightred            #ff3236                ~        LightRed
" Color: brightgreen          #34ee34                ~        LightGreen
" Color: brightyellow         #ffa552                ~        LightYellow
" Color: brightblue           #428ecf                ~        LightBlue
" Color: brightmagenta        #ec4fb1                ~        LightMagenta
" Color: brightcyan           #4bcbcf                ~        LightCyan
" Color: brightwhite          #ededed                ~        White
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" Background: any
" vim: et ts=2 sw=2
